name: Pull Requests

on:
  pull_request:

jobs:
  typescript-build:
    uses: ./.github/workflows/typescript-build.yml

  typescript-test:
    uses: ./.github/workflows/typescript-test.yml

  # Needed for grouping strategies into one check for mergify
  all-pr-checks:
    runs-on: ubuntu-latest
    needs: [typescript-build, typescript-test]
    steps:
      - run: echo "Done"
