name: TypeScript Test

on:
  workflow_call:

env:
  DO_NOT_TRACK: '1'
  TURBO_CONCURRENCY: 1

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 'current'
          - 'lts/*'

    name: Test & Lint on Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies
        with:
          version: ${{ matrix.node }}

      - name: Build
        run: pnpm build

      - name: Test & Lint
        run: pnpm test
