name: TypeScript Test

on:
  workflow_call:

env:
  DO_NOT_TRACK: '1'
  TURBO_CONCURRENCY: 1

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - '22.12.0'
          - 'current'
          - 'lts/*'

    name: Test & Lint on Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies
        with:
          version: ${{ matrix.node }}

      - name: Build
        run: pnpm build

      - name: Test & Lint
        run: pnpm test
